### ISSUE TITLE
Błąd 505 podczas instalacji

### ISSUE THREAD

**Issue by TheMikol** [Gamesites-pl/GameSitesSellIssue#44]
Po kliknięciu przycisku "instalacja" wyrzuciło błąd 500, od tego momentu nie można nic zrobić
![Screenshot_14](https://user-images.githubusercontent.com/81864143/163832194-6113a17a-11d0-4bf6-aa38-00b0d7f049fc.png)
,

**Comment by Adexion** [comment]
Naprawione, powodem był znak specjalny jakim jest, zostało to naprawione, znaki specjalne w nazwie będą w przyszłości ucinane.
