### ISSUE TITLE
Dodatki do różowej templatki

### ISSUE THREAD

**Issue by TheMikol** [Gamesites-pl/GameSitesSellIssue#45]
**1**. Dodać do elementu "Skopiuj IP" odsyłacz do facebooka
![image](https://user-images.githubusercontent.com/81864143/164991437-a56b46c1-1102-4ec5-b63b-a2b62994b311.png)
**2**. Możliwość swobodnego edytowania topki (ilość graczy online, ilość banów, zakupionych ogólnie etc. itd.)
![image](https://user-images.githubusercontent.com/81864143/164991444-e5d6d117-9dc3-4b65-b68b-36abeaead93b.png)
**3**. Dodanie mety "keywords" oraz property np. "og:image" aby podgląd był ładniejszy (moja zapasowa domena z tymi "tagami")
![image](https://user-images.githubusercontent.com/81864143/164994879-dfad0fa5-56aa-4b22-8639-f0cea018036c.png)
**4**. Jak już wszystko po polsku to preferuje /bany zamiast /bans, /sklep zamiast /shop etc. 🥴

__________
**1**. Indywidualna prośba - wyśrodkować element "skopiuj IP" na wysepkę, ew. w ustawieniach dodać opcje czy element ma być wyśrodkowany/ z lewej/prawej strony.
![image](https://user-images.githubusercontent.com/81864143/164991468-90005186-c7f9-4bd3-ac92-94004afae9cb.png)

**Comment by Adexion** [comment]
3. Także ukończone,
pkt 2 przerzucam do osobnego issue
