### ISSUE TITLE
Nie działające funkcje - regulamin i artykuły

### ISSUE THREAD

**Issue by TheMikol** [Gamesites-pl/GameSitesSellIssue#46]
**1**. Nie można wrzucić obrazka do regulaminu/wywala błąd 500
**2**. Po zrobieniu i zapisaniu regulaminu, na stronie (menu) nie przenosi nas do podstrony z regulaminem
**3**. Gdzie zapisują się artykuły?, zrobiłem jeden testowy i nie ma go na stronie

**Comment by Adexion** [comment]
1. Proszę o kontakt w celu odtworzenia błędu.
2. Zrobione
3. Na obecnej templatce Artykuły nie są jeszcze dostępne. Zostaną udostępnione w najbliższym możliwym terminie

**Comment by Adexion** [comment]
1. Błąd CKEditora, nie będzie takiej możliwości. Przycisk nie ma żadnego działania.
3. Przenoszę do osobnego issue
